project_id = "wkalfrdwtfbddolepkoa"

[functions.asaas-webhook]
verify_jwt = false

[functions.create-payment]
verify_jwt = true

[functions.payment-status]
verify_jwt = true
[functions.force-confirm-payment]
verify_jwt = true
